name: build artifacts

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set short git commit SHA
      id: vars
      run: |
        calculated_sha=$(git rev-parse --short ${{ github.sha }})
        echo "COMMIT_SHORT_SHA=$calculated_sha" >> $GITHUB_ENV

    - name: Confirm git commit SHA output
      run: echo ${{ env.COMMIT_SHORT_SHA }}

    - name: build release
      env:
        CI: true
      run: ./scripts/build.sh
