name: Release

on:
  push:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: set version
      id: vars
      run: |
        rel_version=$(date +'%Y-%m-%d.%H%M%S')
        echo "RELEASE_VERSION=$rel_version" >> $GITHUB_ENV

    - name: build release
      env:
        CI: true
      run: ./scripts/build.sh

    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: false
        release_name: ${{ env.RELEASE_VERSION }}
        tag_name: ${{ env.RELEASE_VERSION }}
        body: ""

    - name: upload artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/hacs.zip
        asset_name: hacs.zip
        asset_content_type: application/zip